branch-defaults:
  anisha:
    environment: Msia423Example-env
  master:
    environment: cuisine-dev
environment-defaults:
  Msia423Example-env:
    branch: null
    repository: null
  cuisine-dev:
    branch: null
    repository: null
global:
  application_name: msia423-example
  default_ec2_keyname: aws-eb
  default_platform: arn:aws:elasticbeanstalk:us-east-2::platform/Python 3.6 running
    on 64bit Amazon Linux/2.6.5
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
